<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8f737dc8-94ac-4ac5-8c89-3e88e37256d7</UserSecretsId>
    <RestoreEnablePackagePruning>false</RestoreEnablePackagePruning>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Elasticsearch" Version="13.3.0" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.5" />
    <PackageReference Include="Fractions" Version="7.3.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.5" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.5" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.4.5" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.5" />
    <PackageReference Include="Scalar.Aspire" Version="0.10.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Microservices\Identity\Identity.API\Identity.API.csproj" />
    <ProjectReference Include="..\..\Gateways\ApiGateway\ApiGateway.csproj" />
    <ProjectReference Include="..\..\Microservices\Catalog\Catalog.API\Catalog.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Search\Search.API\Search.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Inventory\Inventory.API\Inventory.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Cart\Cart.API\Cart.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Ordering\Ordering.API\Ordering.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Payment\Payment.API\Payment.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Notification\Notification.Worker\Notification.Worker.csproj" />
    <ProjectReference Include="..\..\Microservices\StoreManagement\StoreManagement.API\StoreManagement.API.csproj" />
    <ProjectReference Include="..\..\Microservices\Media\Media.API\Media.API.csproj" />
    <ProjectReference Include="..\..\Tools\Seeder.App\Seeder.App.csproj" />
  </ItemGroup>

</Project>
