using System.Text.Json.Serialization;

namespace Seeder.App.Models;

// ── Input Models (loaded from JSON seed data) ──────────────────

/// <summary>User seed data from users.json.</summary>
public record UserModel(string Email, string Password, string FirstName, string LastName, string Role);

/// <summary>Store seed data from stores.json.</summary>
public record StoreModel(string SellerEmail, string SellerPassword, string Name, string Description);

/// <summary>
/// Category seed data from categories.json.
/// Includes optional attribute definitions to create on the category.
/// ParentCategoryName links to a parent by name (resolved at runtime).
/// </summary>
public record CategoryModel(
    string Name,
    string Description,
    Guid? ParentCategoryId = null,
    [property: JsonPropertyName("ParentCategoryName")]
    string? ParentCategoryName = null,
    [property: JsonPropertyName("AttributeDefinitions")]
    List<AttributeDefinitionModel>? AttributeDefinitions = null);

/// <summary>
/// Attribute definition seed data for a category.
/// Declares which attributes products/SKUs in this category must or may have.
/// </summary>
public record AttributeDefinitionModel(
    string Key,
    string DisplayName,
    int Target,        // 0=Product, 1=Sku
    int ValueType,     // 0=Text, 1=Number, 2=Select
    bool IsFilterable,
    bool IsRequired,
    int SortOrder = 0,
    List<string>? AllowedValues = null,
    bool IsVariantAxis = false
);

/// <summary>
/// Product seed data from products.json.
/// Generated by Rozetka scraper or manually created.
/// </summary>
public record ProductModel(
    string StoreName,
    string CategoryName,
    string Name,
    string Description,
    decimal Price,
    string Currency,
    string Sku,
    string[] Tags,
    string ImageUrl,
    int InitialStock,
    string RozetkaCode = "",
    string CategoryPath = "",
    [property: JsonPropertyName("Gallery")] List<string>? Gallery = null,
    [property: JsonPropertyName("Breadcrumbs")] List<BreadcrumbDto>? Breadcrumbs = null,
    [property: JsonPropertyName("Variants")] List<VariantModel>? Variants = null,
    [property: JsonPropertyName("VariantAxes")] Dictionary<string, List<string>>? VariantAxes = null,
    [property: JsonPropertyName("Brand")] string? Brand = null,
    [property: JsonPropertyName("Subtitle")] string? Subtitle = null,
    [property: JsonPropertyName("Availability")] string? Availability = null,
    [property: JsonPropertyName("Warranty")] string? Warranty = null,
    [property: JsonPropertyName("Attributes")] List<TypedAttributeModel>? Attributes = null
);

/// <summary>
/// Typed attribute from the scraper.
/// Type determines how the value is handled:
/// - "selectable": user can choose (from variant selectors)
/// - "number": numeric with optional unit
/// - "text": free text
/// - "boolean": yes/no
/// - "list": multiple values
/// - "color": normalized color name
/// - "resolution": dimensions
/// </summary>
public record TypedAttributeModel(
    [property: JsonPropertyName("key")] string Key,
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("normalized")] string? Normalized = null
);

/// <summary>
/// Variant (SKU) data within a product.
/// Each variant represents a sellable option (e.g., color, storage size).
/// </summary>
public record VariantModel(
    string RozetkaCode,
    string Name,
    string Type,
    decimal Price,
    string ImageUrl = "",
    [property: JsonPropertyName("Gallery")] List<string>? Gallery = null,
    [property: JsonPropertyName("Attributes")] Dictionary<string, string>? Attributes = null
);

/// <summary>Breadcrumb navigation data from Rozetka product pages.</summary>
public record BreadcrumbDto(
    string Name,
    string? Url = null,
    int Position = 0
);

// ── API Response Models ────────────────────────────────────────

/// <summary>JWT token response from Identity API.</summary>
public record LoginResponse(string AccessToken);

/// <summary>Category response from Catalog API.</summary>
public record CategoryDto { public Guid Id { get; set; } public string Name { get; set; } = ""; }

/// <summary>User response from Identity API.</summary>
public record UserDto { public Guid Id { get; set; } public string Email { get; set; } = ""; public string Role { get; set; } = ""; }

/// <summary>Store response from StoreManagement API.</summary>
public record StoreDto { public Guid Id { get; set; } public string Name { get; set; } = ""; public string VerificationStatus { get; set; } = ""; }

/// <summary>Product response from Catalog API.</summary>
public record ProductDto { public Guid Id { get; set; } }

/// <summary>SKU response from Catalog API.</summary>
public record SkuResponseDto { public Guid Id { get; set; } public string SkuCode { get; set; } = ""; }

/// <summary>Product with its SKUs from Catalog API.</summary>
public record ProductWithSkusDto { public Guid Id { get; set; } public List<SkuResponseDto>? Skus { get; set; } }

/// <summary>Inventory item response from Inventory API.</summary>
public record InventoryItemDto(string Sku, int AvailableQuantity);
