using System.Text.Json.Serialization;

namespace Seeder.App.Models;

// ── Input Models (loaded from JSON seed data) ──────────────────

/// <summary>User seed data from users.json.</summary>
public record UserModel(string Email, string Password, string FirstName, string LastName, string Role);

/// <summary>Store seed data from stores.json.</summary>
public record StoreModel(string SellerEmail, string SellerPassword, string Name, string Description);

/// <summary>Category seed data from categories.json.</summary>
public record CategoryModel(string Name, string Description, Guid? ParentCategoryId = null);

/// <summary>
/// Product seed data from products.json.
/// Generated by Rozetka scraper or manually created.
/// </summary>
public record ProductModel(
    string StoreName,
    string CategoryName,
    string Name,
    string Description,
    decimal Price,
    string Currency,
    string Sku,
    string[] Tags,
    string ImageUrl,
    int InitialStock,
    string RozetkaCode = "",
    string CategoryPath = "",
    [property: JsonPropertyName("Gallery")] List<string>? Gallery = null,
    [property: JsonPropertyName("Breadcrumbs")] List<BreadcrumbDto>? Breadcrumbs = null,
    [property: JsonPropertyName("Variants")] List<VariantModel>? Variants = null
);

/// <summary>
/// Variant (SKU) data within a product.
/// Each variant represents a sellable option (e.g., color, storage size).
/// </summary>
public record VariantModel(
    string RozetkaCode,
    string Name,
    string Type,
    decimal Price,
    string ImageUrl = "",
    [property: JsonPropertyName("Gallery")] List<string>? Gallery = null
);

/// <summary>Breadcrumb navigation data from Rozetka product pages.</summary>
public record BreadcrumbDto(
    string Name,
    string? Url = null,
    int Position = 0
);

// ── API Response Models ────────────────────────────────────────

/// <summary>JWT token response from Identity API.</summary>
public record LoginResponse(string AccessToken);

/// <summary>Category response from Catalog API.</summary>
public record CategoryDto { public Guid Id { get; set; } public string Name { get; set; } = ""; }

/// <summary>User response from Identity API.</summary>
public record UserDto { public Guid Id { get; set; } public string Email { get; set; } = ""; public string Role { get; set; } = ""; }

/// <summary>Store response from StoreManagement API.</summary>
public record StoreDto { public Guid Id { get; set; } public string Name { get; set; } = ""; public string VerificationStatus { get; set; } = ""; }

/// <summary>Product response from Catalog API.</summary>
public record ProductDto { public Guid Id { get; set; } }

/// <summary>SKU response from Catalog API.</summary>
public record SkuResponseDto { public Guid Id { get; set; } public string SkuCode { get; set; } = ""; }

/// <summary>Product with its SKUs from Catalog API.</summary>
public record ProductWithSkusDto { public Guid Id { get; set; } public List<SkuResponseDto>? Skus { get; set; } }

/// <summary>Inventory item response from Inventory API.</summary>
public record InventoryItemDto(string Sku, int AvailableQuantity);
