namespace BuildingBlocks.SharedContracts.Abstractions;

/// <summary>
/// Base class for all entities with identity.
/// The ID is generated by EF Core on insert using Guid v7 (time-ordered).
/// Internal setter allows tests to assign IDs for in-memory scenarios.
/// </summary>
public abstract class Entity
{
    public Guid Id { get; internal set; }

    public override bool Equals(object? obj) =>
        obj is Entity other && Id == other.Id;

    public override int GetHashCode() => Id.GetHashCode();
}
